INSERT INTO budgets.income (user_id, category_id, amount, date) values (1, 1, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (1, 2, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (1, 3, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (1, 4, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (2, 5, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (2, 6, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (2, 7, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (1, 8, 0, '1-Jan-2025');
INSERT INTO budgets.income (user_id, category_id, amount, date) values (1, 9, 0, '1-Jan-2025');
commit;