INSERT INTO budgets.expenses ( category_id, amount, date) values ( 35, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 36, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 37, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 38, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 39, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 40, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 41, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 42, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 43, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 44, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 45, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 46, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 47, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 48, 0, '1-Jan-2025');
INSERT INTO budgets.expenses ( category_id, amount, date) values ( 49, 0, '1-Jan-2025');
commit;
